### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by grero** [grero/PanGUI#3]
It would be helpful if we could add some thoughts on what we want PanGUI to do here.
- [X] Pan through a list of objects, calling plot on each of them
- [ ] Specify object specific plot options
- [x] Combine multiple objects per plot
